<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Addition" targetNamespace="http://Addition" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://Addition" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="AdditionHttpBinding" originalBindingStyle="document"/>
        <generatedXSD location="Addition_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  
  <wsdl:types>
    
        <xsd:schema targetNamespace="http://Addition" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
      <xsd:include schemaLocation="Addition_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="AddRequestMsg">
    <wsdl:part element="tns:Add" name="AddParameters"/>
  </wsdl:message>
  <wsdl:message name="AddResponseMsg">
    <wsdl:part element="tns:AddResponse" name="AddResult"/>
  </wsdl:message>
  <wsdl:portType name="Addition">
    <wsdl:operation name="Add">
            <wsdl:input message="tns:AddRequestMsg" name="AddRequest"/>
            <wsdl:output message="tns:AddResponseMsg" name="AddResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AdditionHttpBinding" type="tns:Addition">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Add">
            <soap:operation soapAction="http://Addition/Add"/>
            <wsdl:input name="AddRequest">
                <soap:body use="literal"/>
            </wsdl:input>
      <wsdl:output name="AddResponse">
                <soap:body use="literal"/>
            </wsdl:output>
    </wsdl:operation>
    </wsdl:binding>
  <wsdl:service name="AdditionHttpService">
    <wsdl:port binding="tns:AdditionHttpBinding" name="AdditionHttpPort">
      <soap:address location="http://localhost:7800/Addition"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>