<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="First" targetNamespace="http://First" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://First" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="FirstHttpBinding" originalBindingStyle="document"/>
        <generatedXSD location="First_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    
        <xsd:schema targetNamespace="http://First" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
      <xsd:include schemaLocation="First_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="CalculatorRequestMsg">
    <wsdl:part element="tns:Calculator" name="CalculatorParameters"/>
  </wsdl:message>
  <wsdl:message name="CalculatorResponseMsg">
    <wsdl:part element="tns:CalculatorResponse" name="CalculatorResult"/>
  </wsdl:message>
  <wsdl:portType name="First">
    <wsdl:operation name="Calculator">
            <wsdl:input message="tns:CalculatorRequestMsg" name="CalculatorRequest"/>
            <wsdl:output message="tns:CalculatorResponseMsg" name="CalculatorResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FirstHttpBinding" type="tns:First">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Calculator">
      <soap:operation soapAction="http://First/Calculator"/>
      <wsdl:input name="CalculatorRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="CalculatorResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    </wsdl:binding>
  <wsdl:service name="FirstHttpService">
    <wsdl:port binding="tns:FirstHttpBinding" name="FirstHttpPort">
      <soap:address location="http://localhost:7800/First"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>